language: node_js
node_js:
  - "6"
before_install:
  - npm install -g phantomjs
env:
  global:
    - secure: gGwalTlWUM7/AZlkWzFTcfQorHSy0ENaAOPaSa98w/V2XcK0TMthLv6ZNjtIKzeFkXx2di+o77+0BI3o04adHgNnV1XT30WxSwbk9kOgwVc46z+5OObyHdcp+vJUxeBmMVlVK4R80yfxaK1QAkmognZ0sRy+UvijDg6RF5hFLoA=
    - secure: KUuknlU27hTpPd3DqDp2ZxDQKkArWsqpzj9XClO4hyn3AanpIbHdzIcdn25UF9dsipRS4dZ0oaofeuW9ldoIIK0S5SOUAC8YfNWnaA7eC7CO0hpH88jepSaFTtmFJEBVEKx5TxfFiNVNFrehP3HwLdvX9UPPchvCy6CM+hOf+cI=
